//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchingByAuthor
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookSet()
        {
            this.AuthorSet = new HashSet<AuthorSet>();
        }
    
        public int Id { get; set; }
        public string BookName { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UserSet UserSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorSet> AuthorSet { get; set; }
    }
}
